export const availableFields = [
  "tensaoFaseNeutroA",
  "tensaoFaseNeutroB",
  "tensaoFaseNeutroC",
  "tensaoFaseFaseAB",
  "tensaoFaseFaseBC",
  "tensaoFaseFaseCA",
  "frequencia",
  "correnteA",
  "correnteB",
  "correnteC",
  "correnteNeutroMedido",
  "correnteNeutroCalculado",
  "potenciaAparenteA",
  "potenciaAparenteB",
  "potenciaAparenteC",
  "potenciaAparenteTotalAritmetica",
  "potenciaAparenteTotalVetorial",
  "potenciaAtivaFundamentalA",
  "potenciaAtivaHarmonicaA",
  "potenciaAtivaFundamentalHarmonicaA",
  "potenciaAtivaFundamentalB",
  "potenciaAtivaHarmonicaB",
  "potenciaAtivaFundamentalHarmonicaB",
  "potenciaAtivaFundamentalC",
  "potenciaAtivaHarmonicaC",
  "potenciaAtivaFundamentalHarmonicaC",
  "potenciaAtivaFundamentalTotal",
  "potenciaAtivaHarmonicaTotal",
  "potenciaAtivaFundamentalHarmonicaTotal",
  "potenciaReativaA",
  "potenciaReativaB",
  "potenciaReativaC",
  "potenciaReativaTotalAritmetica",
  "potenciaReativaTotalVetorial",
  "anguloFaseA",
  "anguloFaseB",
  "anguloFaseC",
  "phiFaseA",
  "phiFaseB",
  "phiFaseC",
  "fpRealFaseA",
  "fpRealFaseB",
  "fpRealFaseC",
  "fpRealTotalAritmetica",
  "fpRealTotalVetorial",
  "fpDeslocamentoFaseA",
  "fpDeslocamentoFaseB",
  "fpDeslocamentoFaseC",
  "fpDeslocamentoTotal",
  "thdTensaoA",
  "thdTensaoB",
  "thdTensaoC",
  "thdCorrenteA",
  "thdCorrenteB",
  "thdCorrenteC",
  "temperaturaSensorInterno",
] as const

export const fieldMapping: Record<string, string> = {
  anguloFaseA: "angulo_fase_a",
  anguloFaseB: "angulo_fase_b",
  anguloFaseC: "angulo_fase_c",
  correnteA: "corrente_a",
  correnteB: "corrente_b",
  correnteC: "corrente_c",
  correnteNeutroCalculado: "corrente_de_neutro_calculado",
  correnteNeutroMedido: "corrente_de_neutro_medido",
  fpDeslocamentoFaseA: "fp_deslocamento_fase_a",
  fpDeslocamentoFaseB: "fp_deslocamento_fase_b",
  fpDeslocamentoFaseC: "fp_deslocamento_fase_c",
  fpDeslocamentoTotal: "fp_deslocamento_total",
  fpRealFaseA: "fp_real_fase_a",
  fpRealFaseB: "fp_real_fase_b",
  fpRealFaseC: "fp_real_fase_c",
  fpRealTotalAritmetica: "fp_real_total_soma_aritmetica",
  fpRealTotalVetorial: "fp_real_total_soma_vetorial",
  frequencia: "frequencia",
  phiFaseA: "phi_fase_a",
  phiFaseB: "phi_fase_b",
  phiFaseC: "phi_fase_c",
  potenciaAparenteA: "potencia_aparente_a",
  potenciaAparenteB: "potencia_aparente_b",
  potenciaAparenteC: "potencia_aparente_c",
  potenciaAparenteTotalAritmetica: "potencia_aparente_total_soma_aritmetica",
  potenciaAparenteTotalVetorial: "potencia_aparente_total_soma_vetorial",
  potenciaAtivaFundamentalA: "potencia_ativa_fundamental_a",
  potenciaAtivaFundamentalB: "potencia_ativa_fundamental_b",
  potenciaAtivaFundamentalC: "potencia_ativa_fundamental_c",
  potenciaAtivaFundamentalHarmonicaA: "potencia_ativa_fundamental_harmonica_a",
  potenciaAtivaFundamentalHarmonicaB: "potencia_ativa_fundamental_harmonica_b",
  potenciaAtivaFundamentalHarmonicaC: "potencia_ativa_fundamental_harmonica_c",
  potenciaAtivaFundamentalHarmonicaTotal:
    "potencia_ativa_fundamental_harmonica_total",
  potenciaAtivaFundamentalTotal: "potencia_ativa_fundamental_total",
  potenciaAtivaHarmonicaA: "potencia_ativa_harmonica_a",
  potenciaAtivaHarmonicaB: "potencia_ativa_harmonica_b",
  potenciaAtivaHarmonicaC: "potencia_ativa_harmonica_c",
  potenciaAtivaHarmonicaTotal: "potencia_ativa_harmonica_total",
  potenciaReativaA: "potencia_reativa_a",
  potenciaReativaB: "potencia_reativa_b",
  potenciaReativaC: "potencia_reativa_c",
  potenciaReativaTotalAritmetica: "potencia_reativa_total_soma_aritmetica",
  potenciaReativaTotalVetorial: "potencia_reativa_total_soma_vetorial",
  temperaturaSensorInterno: "temperatura_sensor_interno",
  tensaoFaseFaseAB: "tensao_fase_fase_ab",
  tensaoFaseFaseBC: "tensao_fase_fase_bc",
  tensaoFaseFaseCA: "tensao_fase_fase_ca",
  tensaoFaseNeutroA: "tensao_fase_neutro_a",
  tensaoFaseNeutroB: "tensao_fase_neutro_b",
  tensaoFaseNeutroC: "tensao_fase_neutro_c",
  thdCorrenteA: "thd_corrente_a",
  thdCorrenteB: "thd_corrente_b",
  thdCorrenteC: "thd_corrente_c",
  thdTensaoA: "thd_tensao_a",
  thdTensaoB: "thd_tensao_b",
  thdTensaoC: "thd_tensao_c",
}
