export const availableFields = [
  'tensaoFaseNeutroA',
  'tensaoFaseNeutroB',
  'tensaoFaseNeutroC',
  'tensaoFaseFaseAB',
  'tensaoFaseFaseBC',
  'tensaoFaseFaseCA',
  'frequencia',
  'correnteA',
  'correnteB',
  'correnteC',
  'correnteNeutroMedido',
  'correnteNeutroCalculado',
  'potenciaAparenteA',
  'potenciaAparenteB',
  'potenciaAparenteC',
  'potenciaAparenteTotalAritmetica',
  'potenciaAparenteTotalVetorial',
  'potenciaAtivaFundamentalA',
  'potenciaAtivaHarmonicaA',
  'potenciaAtivaFundamentalHarmonicaA',
  'potenciaAtivaFundamentalB',
  'potenciaAtivaHarmonicaB',
  'potenciaAtivaFundamentalHarmonicaB',
  'potenciaAtivaFundamentalC',
  'potenciaAtivaHarmonicaC',
  'potenciaAtivaFundamentalHarmonicaC',
  'potenciaAtivaFundamentalTotal',
  'potenciaAtivaHarmonicaTotal',
  'potenciaAtivaFundamentalHarmonicaTotal',
  'potenciaReativaA',
  'potenciaReativaB',
  'potenciaReativaC',
  'potenciaReativaTotalAritmetica',
  'potenciaReativaTotalVetorial',
  'anguloFaseA',
  'anguloFaseB',
  'anguloFaseC',
  'phiFaseA',
  'phiFaseB',
  'phiFaseC',
  'fpRealFaseA',
  'fpRealFaseB',
  'fpRealFaseC',
  'fpRealTotalAritmetica',
  'fpRealTotalVetorial',
  'fpDeslocamentoFaseA',
  'fpDeslocamentoFaseB',
  'fpDeslocamentoFaseC',
  'fpDeslocamentoTotal',
  'thdTensaoA',
  'thdTensaoB',
  'thdTensaoC',
  'thdCorrenteA',
  'thdCorrenteB',
  'thdCorrenteC',
  'temperaturaSensorInterno',
] as const

export const fieldMapping: Record<string, string> = {
  tensaoFaseNeutroA: 'tensao_fase_neutro_a',
  tensaoFaseNeutroB: 'tensao_fase_neutro_b',
  tensaoFaseNeutroC: 'tensao_fase_neutro_c',
  tensaoFaseFaseAB: 'tensao_fase_fase_ab',
  tensaoFaseFaseBC: 'tensao_fase_fase_bc',
  tensaoFaseFaseCA: 'tensao_fase_fase_ca',
  frequencia: 'frequencia',
  correnteA: 'corrente_a',
  correnteB: 'corrente_b',
  correnteC: 'corrente_c',
  correnteNeutroMedido: 'corrente_de_neutro_medido',
  correnteNeutroCalculado: 'corrente_de_neutro_calculado',
  potenciaAparenteA: 'potencia_aparente_a',
  potenciaAparenteB: 'potencia_aparente_b',
  potenciaAparenteC: 'potencia_aparente_c',
  potenciaAparenteTotalAritmetica: 'potencia_aparente_total_soma_aritmetica',
  potenciaAparenteTotalVetorial: 'potencia_aparente_total_soma_vetorial',
  potenciaAtivaFundamentalA: 'potencia_ativa_fundamental_a',
  potenciaAtivaHarmonicaA: 'potencia_ativa_harmonica_a',
  potenciaAtivaFundamentalHarmonicaA: 'potencia_ativa_fundamental_harmonica_a',
  potenciaAtivaFundamentalB: 'potencia_ativa_fundamental_b',
  potenciaAtivaHarmonicaB: 'potencia_ativa_harmonica_b',
  potenciaAtivaFundamentalHarmonicaB: 'potencia_ativa_fundamental_harmonica_b',
  potenciaAtivaFundamentalC: 'potencia_ativa_fundamental_c',
  potenciaAtivaHarmonicaC: 'potencia_ativa_harmonica_c',
  potenciaAtivaFundamentalHarmonicaC: 'potencia_ativa_fundamental_harmonica_c',
  potenciaAtivaFundamentalTotal: 'potencia_ativa_fundamental_total',
  potenciaAtivaHarmonicaTotal: 'potencia_ativa_harmonica_total',
  potenciaAtivaFundamentalHarmonicaTotal:
    'potencia_ativa_fundamental_harmonica_total',
  potenciaReativaA: 'potencia_reativa_a',
  potenciaReativaB: 'potencia_reativa_b',
  potenciaReativaC: 'potencia_reativa_c',
  potenciaReativaTotalAritmetica: 'potencia_reativa_total_soma_aritmetica',
  potenciaReativaTotalVetorial: 'potencia_reativa_total_soma_vetorial',
  anguloFaseA: 'angulo_fase_a',
  anguloFaseB: 'angulo_fase_b',
  anguloFaseC: 'angulo_fase_c',
  phiFaseA: 'phi_fase_a',
  phiFaseB: 'phi_fase_b',
  phiFaseC: 'phi_fase_c',
  fpRealFaseA: 'fp_real_fase_a',
  fpRealFaseB: 'fp_real_fase_b',
  fpRealFaseC: 'fp_real_fase_c',
  fpRealTotalAritmetica: 'fp_real_total_soma_aritmetica',
  fpRealTotalVetorial: 'fp_real_total_soma_vetorial',
  fpDeslocamentoFaseA: 'fp_deslocamento_fase_a',
  fpDeslocamentoFaseB: 'fp_deslocamento_fase_b',
  fpDeslocamentoFaseC: 'fp_deslocamento_fase_c',
  fpDeslocamentoTotal: 'fp_deslocamento_total',
  thdTensaoA: 'thd_tensao_a',
  thdTensaoB: 'thd_tensao_b',
  thdTensaoC: 'thd_tensao_c',
  thdCorrenteA: 'thd_corrente_a',
  thdCorrenteB: 'thd_corrente_b',
  thdCorrenteC: 'thd_corrente_c',
  temperaturaSensorInterno: 'temperatura_sensor_interno',
}
