# ------------ BUILDER ------------
FROM node:20 AS builder

WORKDIR /app

# copiar o monorepo inteiro (necessário p/ pnpm workspace)
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./

COPY apps ./apps
COPY packages ./packages

RUN corepack enable
RUN pnpm install --frozen-lockfile

# build do web
WORKDIR /app/apps/web
RUN pnpm build

# ------------ RUNTIME (NGINX) ------------
FROM nginx:alpine AS runner

WORKDIR /usr/share/nginx/html

# limpar HTML padrão do nginx
RUN rm -rf ./*

# copiar artefatos do build vite
COPY --from=builder /app/apps/web/dist ./

# copiar config nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
