use axum::{
    body::Body,
    http::{self, Request, StatusCode},
};
use axum_server::{AppState, create_app};
use http_body_util::BodyExt;
use serde_json::{Value, json};
use std::time::Instant;
use tower::ServiceExt;

/// Factory pattern for creating authentication tokens directly in memory for test scenarios.
/// This pattern avoids executing database `SELECT` queries on the user table and CPU-bound Argon2 password hashing.
pub struct AuthTokenFactory {
    jwt_secret: String,
}

impl AuthTokenFactory {
    pub fn new(jwt_secret: impl Into<String>) -> Self {
        Self {
            jwt_secret: jwt_secret.into(),
        }
    }

    /// Mint a signed JWT token directly using the secret key in memory.
    ///
    /// # Avoided Operations:
    /// - Database SELECT query on user credentials
    /// - Argon2 CPU-expensive password hashing
    pub fn create_token(&self, user_id: &str) -> String {
        axum_server::auth::create_jwt(user_id, &self.jwt_secret)
            .expect("Factory should successfully create valid JWT token")
    }

    /// Create an `Authorization: Bearer <token>` header value.
    pub fn bearer_header(&self, user_id: &str) -> String {
        format!("Bearer {}", self.create_token(user_id))
    }
}

/// Test application factory providing configured Axum router and auth factory.
pub struct TestAppFactory {
    pub jwt_secret: String,
    pub auth_factory: AuthTokenFactory,
}

impl TestAppFactory {
    pub fn new() -> Self {
        let jwt_secret = "test_jwt_secret_key_987654321".to_string();
        let auth_factory = AuthTokenFactory::new(jwt_secret.clone());
        Self {
            jwt_secret,
            auth_factory,
        }
    }

    /// Creates a fresh instance of the Axum app router for testing.
    pub fn create_router(&self) -> axum::Router {
        let pool = sqlx::postgres::PgPoolOptions::new()
            .connect_lazy("postgres://postgres:postgres@localhost:5432/test_db")
            .expect("Lazy pool creation should succeed");

        let state = AppState {
            db: pool,
            jwt_secret: self.jwt_secret.clone(),
        };

        create_app(state)
    }

    /// Build an authenticated request using token generated by `AuthTokenFactory`.
    pub fn authenticated_request(
        &self,
        method: http::Method,
        uri: &str,
        user_id: &str,
        body: Option<Value>,
    ) -> Request<Body> {
        let bearer = self.auth_factory.bearer_header(user_id);
        let req = Request::builder()
            .method(method)
            .uri(uri)
            .header(http::header::AUTHORIZATION, bearer)
            .header(http::header::CONTENT_TYPE, "application/json");

        if let Some(json_body) = body {
            req.body(Body::from(json_body.to_string())).unwrap()
        } else {
            req.body(Body::empty()).unwrap()
        }
    }

    /// Build an unauthenticated request without Authorization header.
    pub fn unauthenticated_request(
        &self,
        method: http::Method,
        uri: &str,
        body: Option<Value>,
    ) -> Request<Body> {
        let req = Request::builder()
            .method(method)
            .uri(uri)
            .header(http::header::CONTENT_TYPE, "application/json");

        if let Some(json_body) = body {
            req.body(Body::from(json_body.to_string())).unwrap()
        } else {
            req.body(Body::empty()).unwrap()
        }
    }
}

// Helper to parse response body to JSON
async fn response_to_json(response: axum::response::Response) -> Value {
    let bytes = response.into_body().collect().await.unwrap().to_bytes();
    serde_json::from_slice(&bytes).unwrap_or(json!({}))
}

#[tokio::test]
async fn test_get_health_routes() {
    let factory = TestAppFactory::new();
    let app = factory.create_router();

    let req = Request::builder()
        .method("GET")
        .uri("/health")
        .body(Body::empty())
        .unwrap();

    let response = app.oneshot(req).await.unwrap();
    assert_eq!(response.status(), StatusCode::OK);

    let json_res = response_to_json(response).await;
    assert_eq!(json_res, json!({ "status": "ok" }));
}

#[tokio::test]
async fn test_get_openapi_json_basic_auth() {
    let factory = TestAppFactory::new();
    
    // Case 1: Without Basic Auth -> 401 Unauthorized with WWW-Authenticate header
    {
        let app = factory.create_router();
        let req = Request::builder()
            .method("GET")
            .uri("/openapi.json")
            .body(Body::empty())
            .unwrap();
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
        assert!(response.headers().contains_key("www-authenticate"));
    }

    // Case 2: With valid Basic Auth -> 200 OK
    {
        let app = factory.create_router();
        let req = Request::builder()
            .method("GET")
            .uri("/openapi.json")
            .header(http::header::AUTHORIZATION, "Basic YWRtaW46YWRtaW4=") // admin:admin
            .body(Body::empty())
            .unwrap();
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::OK);

        let json_res = response_to_json(response).await;
        assert!(json_res.get("openapi").is_some());
        assert_eq!(json_res["info"]["title"], "LAPES - API");
    }
}

#[tokio::test]
async fn test_get_scalar_docs_basic_auth() {
    let factory = TestAppFactory::new();

    // Case 1: Without Basic Auth -> 401 Unauthorized with WWW-Authenticate header
    {
        let app = factory.create_router();
        let req = Request::builder()
            .method("GET")
            .uri("/docs")
            .body(Body::empty())
            .unwrap();
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
        assert!(response.headers().contains_key("www-authenticate"));
    }

    // Case 2: With valid Basic Auth -> 200 OK
    {
        let app = factory.create_router();
        let req = Request::builder()
            .method("GET")
            .uri("/docs")
            .header(http::header::AUTHORIZATION, "Basic YWRtaW46YWRtaW4=") // admin:admin
            .body(Body::empty())
            .unwrap();
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::OK);
    }
}

#[tokio::test]
async fn test_authenticated_route_access_avoids_db_select_and_hashing() {
    // THIS TEST VALIDATES THAT AUTHENTICATED ROUTES BYPASS DB SELECT AND ARGON2 HASHING
    // BY USING THE FACTORY PATTERN FOR TOKEN GENERATION.
    let factory = TestAppFactory::new();
    let app = factory.create_router();

    let start_time = Instant::now();

    // 1. Generate authentication token via Factory Pattern.
    // Notice: 0 SQL queries executed against "user" table, 0 Argon2 password hash verifications.
    let token = factory.auth_factory.create_token("user-id-12345");
    assert!(!token.is_empty(), "Factory token must not be empty");

    // 2. Dispatch request to authenticated route POST /meters
    let payload = json!({
        "name": "", // Empty name to trigger handler payload validation AFTER AuthUser extractor passes
        "ip": "192.168.1.100",
        "issoSerial": "258-A17-39C-D6A",
        "description": "Test Meter"
    });

    let req = Request::builder()
        .method("POST")
        .uri("/meters")
        .header(http::header::AUTHORIZATION, format!("Bearer {}", token))
        .header(http::header::CONTENT_TYPE, "application/json")
        .body(Body::from(payload.to_string()))
        .unwrap();

    let response = app.oneshot(req).await.unwrap();
    let duration = start_time.elapsed();

    // 3. Assertions confirming authentication passed WITHOUT 401 Unauthorized:
    // Status is 400 Bad Request because handler's payload validation ran.
    // If auth failed, status would be 401 Unauthorized.
    assert_ne!(
        response.status(),
        StatusCode::UNAUTHORIZED,
        "Authentication should pass using factory token without 401 Unauthorized"
    );
    assert_eq!(
        response.status(),
        StatusCode::BAD_REQUEST,
        "Auth pass confirmed; payload validation error returned"
    );

    let json_res = response_to_json(response).await;
    assert_eq!(json_res, json!({ "error": "Meter name is required" }));

    // Factory token creation + auth extraction completed rapidly without Argon2 hashing or DB SELECT queries
    println!(
        "Factory authentication test completed in {:?} (DB SELECT and Argon2 hashing avoided)",
        duration
    );
}

#[tokio::test]
async fn test_create_meter_auth_validation() {
    let factory = TestAppFactory::new();

    // Case 1: Unauthenticated (No Auth Header) -> 401 Unauthorized
    {
        let app = factory.create_router();
        let req = factory.unauthenticated_request(
            http::Method::POST,
            "/meters",
            Some(json!({
                "name": "Meter 1",
                "ip": "192.168.1.1",
                "issoSerial": "258-A17-39C-D6A",
                "description": "Desc"
            })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    // Case 2: Invalid Token -> 401 Unauthorized
    {
        let app = factory.create_router();
        let req = Request::builder()
            .method("POST")
            .uri("/meters")
            .header(http::header::AUTHORIZATION, "Bearer invalid.jwt.token")
            .header(http::header::CONTENT_TYPE, "application/json")
            .body(Body::from(json!({}).to_string()))
            .unwrap();
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    // Case 3: Valid Factory Auth Token + Empty Name -> 400 Bad Request
    {
        let app = factory.create_router();
        let req = factory.authenticated_request(
            http::Method::POST,
            "/meters",
            "test_user",
            Some(json!({
                "name": "   ",
                "ip": "192.168.1.1",
                "issoSerial": "258-A17-39C-D6A",
                "description": "Desc"
            })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let json_res = response_to_json(response).await;
        assert_eq!(json_res, json!({ "error": "Meter name is required" }));
    }

    // Case 4: Valid Factory Auth Token + Invalid IP -> 400 Bad Request
    {
        let app = factory.create_router();
        let req = factory.authenticated_request(
            http::Method::POST,
            "/meters",
            "test_user",
            Some(json!({
                "name": "Valid Meter",
                "ip": "invalid_ip_format",
                "issoSerial": "258-A17-39C-D6A",
                "description": "Desc"
            })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let json_res = response_to_json(response).await;
        assert_eq!(json_res, json!({ "error": "IP inválido" }));
    }

    // Case 5: Valid Factory Auth Token + Invalid Serial -> 400 Bad Request
    {
        let app = factory.create_router();
        let req = factory.authenticated_request(
            http::Method::POST,
            "/meters",
            "test_user",
            Some(json!({
                "name": "Valid Meter",
                "ip": "192.168.1.1",
                "issoSerial": "INVALID-SERIAL",
                "description": "Desc"
            })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let json_res = response_to_json(response).await;
        assert_eq!(
            json_res,
            json!({ "error": "Serial inválido. Formato esperado: 258-A17-39C-D6A" })
        );
    }
}

#[tokio::test]
async fn test_update_meter_auth_validation() {
    let factory = TestAppFactory::new();

    // Case 1: Unauthenticated -> 401 Unauthorized
    {
        let app = factory.create_router();
        let req = factory.unauthenticated_request(
            http::Method::PUT,
            "/meters/1",
            Some(json!({
                "name": "Updated Meter",
                "ip": "192.168.1.2",
                "description": "Updated"
            })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    // Case 2: Factory Token + Empty Name -> 400 Bad Request
    {
        let app = factory.create_router();
        let req = factory.authenticated_request(
            http::Method::PUT,
            "/meters/1",
            "test_user",
            Some(json!({
                "name": "",
                "ip": "192.168.1.2",
                "description": "Updated"
            })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let json_res = response_to_json(response).await;
        assert_eq!(json_res, json!({ "error": "Meter name is required" }));
    }

    // Case 3: Factory Token + Invalid IP -> 400 Bad Request
    {
        let app = factory.create_router();
        let req = factory.authenticated_request(
            http::Method::PUT,
            "/meters/1",
            "test_user",
            Some(json!({
                "name": "Updated Name",
                "ip": "300.300.300.300",
                "description": "Updated"
            })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let json_res = response_to_json(response).await;
        assert_eq!(json_res, json!({ "error": "IP inválido" }));
    }
}

#[tokio::test]
async fn test_update_meter_status_auth_validation() {
    let factory = TestAppFactory::new();

    // Case 1: Unauthenticated -> 401 Unauthorized
    {
        let app = factory.create_router();
        let req = factory.unauthenticated_request(
            http::Method::PATCH,
            "/meter/1",
            Some(json!({ "enabled": true })),
        );
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    // Case 2: Factory Token -> Auth succeeds, passes to handler
    {
        let app = factory.create_router();
        let req = factory.authenticated_request(
            http::Method::PATCH,
            "/meter/1",
            "test_user",
            Some(json!({ "enabled": true })),
        );
        let response = app.oneshot(req).await.unwrap();
        // Auth passed (not 401)
        assert_ne!(response.status(), StatusCode::UNAUTHORIZED);
    }
}

#[tokio::test]
async fn test_delete_meter_auth_validation() {
    let factory = TestAppFactory::new();

    // Case 1: Unauthenticated -> 401 Unauthorized
    {
        let app = factory.create_router();
        let req = factory.unauthenticated_request(http::Method::DELETE, "/meters/1", None);
        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    // Case 2: Factory Token -> Auth succeeds, passes to handler
    {
        let app = factory.create_router();
        let req =
            factory.authenticated_request(http::Method::DELETE, "/meters/1", "test_user", None);
        let response = app.oneshot(req).await.unwrap();
        // Auth passed (not 401)
        assert_ne!(response.status(), StatusCode::UNAUTHORIZED);
    }
}
