/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FullPlanRouteImport } from './routes/full-plan'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as dashboardTelemetriaRouteRouteImport } from './routes/(dashboard)/telemetria/route'
import { Route as dashboardSupervisorioRouteRouteImport } from './routes/(dashboard)/supervisorio/route'
import { Route as dashboardSettingsRouteRouteImport } from './routes/(dashboard)/settings/route'
import { Route as dashboardGrChar225ficosRouteRouteImport } from './routes/(dashboard)/gráficos/route'
import { Route as dashboardTelemetriaIndexRouteImport } from './routes/(dashboard)/telemetria/index'
import { Route as dashboardSupervisorioIndexRouteImport } from './routes/(dashboard)/supervisorio/index'
import { Route as dashboardTelemetriaMeterIdRouteImport } from './routes/(dashboard)/telemetria/$meterId'
import { Route as dashboardSettingsMeterIdRouteImport } from './routes/(dashboard)/settings/$meterId'
import { Route as dashboardTelemetriaMeterIdEditRouteImport } from './routes/(dashboard)/telemetria/$meterId.edit'
import { Route as dashboardTelemetriaMeterIdDeleteRouteImport } from './routes/(dashboard)/telemetria/$meterId.delete'

const FullPlanRoute = FullPlanRouteImport.update({
  id: '/full-plan',
  path: '/full-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTelemetriaRouteRoute =
  dashboardTelemetriaRouteRouteImport.update({
    id: '/telemetria',
    path: '/telemetria',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSupervisorioRouteRoute =
  dashboardSupervisorioRouteRouteImport.update({
    id: '/supervisorio',
    path: '/supervisorio',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSettingsRouteRoute = dashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardGrChar225ficosRouteRoute =
  dashboardGrChar225ficosRouteRouteImport.update({
    id: '/gráficos',
    path: '/gráficos',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTelemetriaIndexRoute =
  dashboardTelemetriaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardTelemetriaRouteRoute,
  } as any)
const dashboardSupervisorioIndexRoute =
  dashboardSupervisorioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardSupervisorioRouteRoute,
  } as any)
const dashboardTelemetriaMeterIdRoute =
  dashboardTelemetriaMeterIdRouteImport.update({
    id: '/$meterId',
    path: '/$meterId',
    getParentRoute: () => dashboardTelemetriaRouteRoute,
  } as any)
const dashboardSettingsMeterIdRoute =
  dashboardSettingsMeterIdRouteImport.update({
    id: '/$meterId',
    path: '/$meterId',
    getParentRoute: () => dashboardSettingsRouteRoute,
  } as any)
const dashboardTelemetriaMeterIdEditRoute =
  dashboardTelemetriaMeterIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => dashboardTelemetriaMeterIdRoute,
  } as any)
const dashboardTelemetriaMeterIdDeleteRoute =
  dashboardTelemetriaMeterIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => dashboardTelemetriaMeterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/full-plan': typeof FullPlanRoute
  '/gráficos': typeof dashboardGrChar225ficosRouteRoute
  '/settings': typeof dashboardSettingsRouteRouteWithChildren
  '/supervisorio': typeof dashboardSupervisorioRouteRouteWithChildren
  '/telemetria': typeof dashboardTelemetriaRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/settings/$meterId': typeof dashboardSettingsMeterIdRoute
  '/telemetria/$meterId': typeof dashboardTelemetriaMeterIdRouteWithChildren
  '/supervisorio/': typeof dashboardSupervisorioIndexRoute
  '/telemetria/': typeof dashboardTelemetriaIndexRoute
  '/telemetria/$meterId/delete': typeof dashboardTelemetriaMeterIdDeleteRoute
  '/telemetria/$meterId/edit': typeof dashboardTelemetriaMeterIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/full-plan': typeof FullPlanRoute
  '/gráficos': typeof dashboardGrChar225ficosRouteRoute
  '/settings': typeof dashboardSettingsRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/settings/$meterId': typeof dashboardSettingsMeterIdRoute
  '/telemetria/$meterId': typeof dashboardTelemetriaMeterIdRouteWithChildren
  '/supervisorio': typeof dashboardSupervisorioIndexRoute
  '/telemetria': typeof dashboardTelemetriaIndexRoute
  '/telemetria/$meterId/delete': typeof dashboardTelemetriaMeterIdDeleteRoute
  '/telemetria/$meterId/edit': typeof dashboardTelemetriaMeterIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/full-plan': typeof FullPlanRoute
  '/(dashboard)/gráficos': typeof dashboardGrChar225ficosRouteRoute
  '/(dashboard)/settings': typeof dashboardSettingsRouteRouteWithChildren
  '/(dashboard)/supervisorio': typeof dashboardSupervisorioRouteRouteWithChildren
  '/(dashboard)/telemetria': typeof dashboardTelemetriaRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/(dashboard)/settings/$meterId': typeof dashboardSettingsMeterIdRoute
  '/(dashboard)/telemetria/$meterId': typeof dashboardTelemetriaMeterIdRouteWithChildren
  '/(dashboard)/supervisorio/': typeof dashboardSupervisorioIndexRoute
  '/(dashboard)/telemetria/': typeof dashboardTelemetriaIndexRoute
  '/(dashboard)/telemetria/$meterId/delete': typeof dashboardTelemetriaMeterIdDeleteRoute
  '/(dashboard)/telemetria/$meterId/edit': typeof dashboardTelemetriaMeterIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/full-plan'
    | '/gráficos'
    | '/settings'
    | '/supervisorio'
    | '/telemetria'
    | '/login'
    | '/settings/$meterId'
    | '/telemetria/$meterId'
    | '/supervisorio/'
    | '/telemetria/'
    | '/telemetria/$meterId/delete'
    | '/telemetria/$meterId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/full-plan'
    | '/gráficos'
    | '/settings'
    | '/login'
    | '/settings/$meterId'
    | '/telemetria/$meterId'
    | '/supervisorio'
    | '/telemetria'
    | '/telemetria/$meterId/delete'
    | '/telemetria/$meterId/edit'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)'
    | '/full-plan'
    | '/(dashboard)/gráficos'
    | '/(dashboard)/settings'
    | '/(dashboard)/supervisorio'
    | '/(dashboard)/telemetria'
    | '/login/'
    | '/(dashboard)/settings/$meterId'
    | '/(dashboard)/telemetria/$meterId'
    | '/(dashboard)/supervisorio/'
    | '/(dashboard)/telemetria/'
    | '/(dashboard)/telemetria/$meterId/delete'
    | '/(dashboard)/telemetria/$meterId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  FullPlanRoute: typeof FullPlanRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/full-plan': {
      id: '/full-plan'
      path: '/full-plan'
      fullPath: '/full-plan'
      preLoaderRoute: typeof FullPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/telemetria': {
      id: '/(dashboard)/telemetria'
      path: '/telemetria'
      fullPath: '/telemetria'
      preLoaderRoute: typeof dashboardTelemetriaRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/supervisorio': {
      id: '/(dashboard)/supervisorio'
      path: '/supervisorio'
      fullPath: '/supervisorio'
      preLoaderRoute: typeof dashboardSupervisorioRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/gráficos': {
      id: '/(dashboard)/gráficos'
      path: '/gráficos'
      fullPath: '/gráficos'
      preLoaderRoute: typeof dashboardGrChar225ficosRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/telemetria/': {
      id: '/(dashboard)/telemetria/'
      path: '/'
      fullPath: '/telemetria/'
      preLoaderRoute: typeof dashboardTelemetriaIndexRouteImport
      parentRoute: typeof dashboardTelemetriaRouteRoute
    }
    '/(dashboard)/supervisorio/': {
      id: '/(dashboard)/supervisorio/'
      path: '/'
      fullPath: '/supervisorio/'
      preLoaderRoute: typeof dashboardSupervisorioIndexRouteImport
      parentRoute: typeof dashboardSupervisorioRouteRoute
    }
    '/(dashboard)/telemetria/$meterId': {
      id: '/(dashboard)/telemetria/$meterId'
      path: '/$meterId'
      fullPath: '/telemetria/$meterId'
      preLoaderRoute: typeof dashboardTelemetriaMeterIdRouteImport
      parentRoute: typeof dashboardTelemetriaRouteRoute
    }
    '/(dashboard)/settings/$meterId': {
      id: '/(dashboard)/settings/$meterId'
      path: '/$meterId'
      fullPath: '/settings/$meterId'
      preLoaderRoute: typeof dashboardSettingsMeterIdRouteImport
      parentRoute: typeof dashboardSettingsRouteRoute
    }
    '/(dashboard)/telemetria/$meterId/edit': {
      id: '/(dashboard)/telemetria/$meterId/edit'
      path: '/edit'
      fullPath: '/telemetria/$meterId/edit'
      preLoaderRoute: typeof dashboardTelemetriaMeterIdEditRouteImport
      parentRoute: typeof dashboardTelemetriaMeterIdRoute
    }
    '/(dashboard)/telemetria/$meterId/delete': {
      id: '/(dashboard)/telemetria/$meterId/delete'
      path: '/delete'
      fullPath: '/telemetria/$meterId/delete'
      preLoaderRoute: typeof dashboardTelemetriaMeterIdDeleteRouteImport
      parentRoute: typeof dashboardTelemetriaMeterIdRoute
    }
  }
}

interface dashboardSettingsRouteRouteChildren {
  dashboardSettingsMeterIdRoute: typeof dashboardSettingsMeterIdRoute
}

const dashboardSettingsRouteRouteChildren: dashboardSettingsRouteRouteChildren =
  {
    dashboardSettingsMeterIdRoute: dashboardSettingsMeterIdRoute,
  }

const dashboardSettingsRouteRouteWithChildren =
  dashboardSettingsRouteRoute._addFileChildren(
    dashboardSettingsRouteRouteChildren,
  )

interface dashboardSupervisorioRouteRouteChildren {
  dashboardSupervisorioIndexRoute: typeof dashboardSupervisorioIndexRoute
}

const dashboardSupervisorioRouteRouteChildren: dashboardSupervisorioRouteRouteChildren =
  {
    dashboardSupervisorioIndexRoute: dashboardSupervisorioIndexRoute,
  }

const dashboardSupervisorioRouteRouteWithChildren =
  dashboardSupervisorioRouteRoute._addFileChildren(
    dashboardSupervisorioRouteRouteChildren,
  )

interface dashboardTelemetriaMeterIdRouteChildren {
  dashboardTelemetriaMeterIdDeleteRoute: typeof dashboardTelemetriaMeterIdDeleteRoute
  dashboardTelemetriaMeterIdEditRoute: typeof dashboardTelemetriaMeterIdEditRoute
}

const dashboardTelemetriaMeterIdRouteChildren: dashboardTelemetriaMeterIdRouteChildren =
  {
    dashboardTelemetriaMeterIdDeleteRoute:
      dashboardTelemetriaMeterIdDeleteRoute,
    dashboardTelemetriaMeterIdEditRoute: dashboardTelemetriaMeterIdEditRoute,
  }

const dashboardTelemetriaMeterIdRouteWithChildren =
  dashboardTelemetriaMeterIdRoute._addFileChildren(
    dashboardTelemetriaMeterIdRouteChildren,
  )

interface dashboardTelemetriaRouteRouteChildren {
  dashboardTelemetriaMeterIdRoute: typeof dashboardTelemetriaMeterIdRouteWithChildren
  dashboardTelemetriaIndexRoute: typeof dashboardTelemetriaIndexRoute
}

const dashboardTelemetriaRouteRouteChildren: dashboardTelemetriaRouteRouteChildren =
  {
    dashboardTelemetriaMeterIdRoute:
      dashboardTelemetriaMeterIdRouteWithChildren,
    dashboardTelemetriaIndexRoute: dashboardTelemetriaIndexRoute,
  }

const dashboardTelemetriaRouteRouteWithChildren =
  dashboardTelemetriaRouteRoute._addFileChildren(
    dashboardTelemetriaRouteRouteChildren,
  )

interface dashboardRouteRouteChildren {
  dashboardGrChar225ficosRouteRoute: typeof dashboardGrChar225ficosRouteRoute
  dashboardSettingsRouteRoute: typeof dashboardSettingsRouteRouteWithChildren
  dashboardSupervisorioRouteRoute: typeof dashboardSupervisorioRouteRouteWithChildren
  dashboardTelemetriaRouteRoute: typeof dashboardTelemetriaRouteRouteWithChildren
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardGrChar225ficosRouteRoute: dashboardGrChar225ficosRouteRoute,
  dashboardSettingsRouteRoute: dashboardSettingsRouteRouteWithChildren,
  dashboardSupervisorioRouteRoute: dashboardSupervisorioRouteRouteWithChildren,
  dashboardTelemetriaRouteRoute: dashboardTelemetriaRouteRouteWithChildren,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  FullPlanRoute: FullPlanRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
