/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FullPlanRouteImport } from './routes/full-plan'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as dashboardSettingsRouteImport } from './routes/(dashboard)/settings'
import { Route as dashboardTelemetriaRouteRouteImport } from './routes/(dashboard)/telemetria/route'
import { Route as dashboardSupervisorioRouteRouteImport } from './routes/(dashboard)/supervisorio/route'
import { Route as dashboardTelemetriaIndexRouteImport } from './routes/(dashboard)/telemetria/index'
import { Route as dashboardSupervisorioIndexRouteImport } from './routes/(dashboard)/supervisorio/index'
import { Route as dashboardGrChar225ficosIndexRouteImport } from './routes/(dashboard)/gráficos/index'
import { Route as dashboardTelemetriaTelemetryIpRouteImport } from './routes/(dashboard)/telemetria/$telemetryIp'
import { Route as dashboardTelemetriaMeterIdEditRouteImport } from './routes/(dashboard)/telemetria/$meterId.edit'
import { Route as dashboardTelemetriaMeterIdDeleteRouteImport } from './routes/(dashboard)/telemetria/$meterId.delete'

const FullPlanRoute = FullPlanRouteImport.update({
  id: '/full-plan',
  path: '/full-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsRoute = dashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardTelemetriaRouteRoute =
  dashboardTelemetriaRouteRouteImport.update({
    id: '/telemetria',
    path: '/telemetria',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSupervisorioRouteRoute =
  dashboardSupervisorioRouteRouteImport.update({
    id: '/supervisorio',
    path: '/supervisorio',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTelemetriaIndexRoute =
  dashboardTelemetriaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardTelemetriaRouteRoute,
  } as any)
const dashboardSupervisorioIndexRoute =
  dashboardSupervisorioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardSupervisorioRouteRoute,
  } as any)
const dashboardGrChar225ficosIndexRoute =
  dashboardGrChar225ficosIndexRouteImport.update({
    id: '/gráficos/',
    path: '/gráficos/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTelemetriaTelemetryIpRoute =
  dashboardTelemetriaTelemetryIpRouteImport.update({
    id: '/$telemetryIp',
    path: '/$telemetryIp',
    getParentRoute: () => dashboardTelemetriaRouteRoute,
  } as any)
const dashboardTelemetriaMeterIdEditRoute =
  dashboardTelemetriaMeterIdEditRouteImport.update({
    id: '/$meterId/edit',
    path: '/$meterId/edit',
    getParentRoute: () => dashboardTelemetriaRouteRoute,
  } as any)
const dashboardTelemetriaMeterIdDeleteRoute =
  dashboardTelemetriaMeterIdDeleteRouteImport.update({
    id: '/$meterId/delete',
    path: '/$meterId/delete',
    getParentRoute: () => dashboardTelemetriaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardRouteRouteWithChildren
  '/full-plan': typeof FullPlanRoute
  '/supervisorio': typeof dashboardSupervisorioRouteRouteWithChildren
  '/telemetria': typeof dashboardTelemetriaRouteRouteWithChildren
  '/settings': typeof dashboardSettingsRoute
  '/telemetria/$telemetryIp': typeof dashboardTelemetriaTelemetryIpRoute
  '/gráficos': typeof dashboardGrChar225ficosIndexRoute
  '/supervisorio/': typeof dashboardSupervisorioIndexRoute
  '/telemetria/': typeof dashboardTelemetriaIndexRoute
  '/telemetria/$meterId/delete': typeof dashboardTelemetriaMeterIdDeleteRoute
  '/telemetria/$meterId/edit': typeof dashboardTelemetriaMeterIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardRouteRouteWithChildren
  '/full-plan': typeof FullPlanRoute
  '/settings': typeof dashboardSettingsRoute
  '/telemetria/$telemetryIp': typeof dashboardTelemetriaTelemetryIpRoute
  '/gráficos': typeof dashboardGrChar225ficosIndexRoute
  '/supervisorio': typeof dashboardSupervisorioIndexRoute
  '/telemetria': typeof dashboardTelemetriaIndexRoute
  '/telemetria/$meterId/delete': typeof dashboardTelemetriaMeterIdDeleteRoute
  '/telemetria/$meterId/edit': typeof dashboardTelemetriaMeterIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/full-plan': typeof FullPlanRoute
  '/(dashboard)/supervisorio': typeof dashboardSupervisorioRouteRouteWithChildren
  '/(dashboard)/telemetria': typeof dashboardTelemetriaRouteRouteWithChildren
  '/(dashboard)/settings': typeof dashboardSettingsRoute
  '/(dashboard)/telemetria/$telemetryIp': typeof dashboardTelemetriaTelemetryIpRoute
  '/(dashboard)/gráficos/': typeof dashboardGrChar225ficosIndexRoute
  '/(dashboard)/supervisorio/': typeof dashboardSupervisorioIndexRoute
  '/(dashboard)/telemetria/': typeof dashboardTelemetriaIndexRoute
  '/(dashboard)/telemetria/$meterId/delete': typeof dashboardTelemetriaMeterIdDeleteRoute
  '/(dashboard)/telemetria/$meterId/edit': typeof dashboardTelemetriaMeterIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/full-plan'
    | '/supervisorio'
    | '/telemetria'
    | '/settings'
    | '/telemetria/$telemetryIp'
    | '/gráficos'
    | '/supervisorio/'
    | '/telemetria/'
    | '/telemetria/$meterId/delete'
    | '/telemetria/$meterId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/full-plan'
    | '/settings'
    | '/telemetria/$telemetryIp'
    | '/gráficos'
    | '/supervisorio'
    | '/telemetria'
    | '/telemetria/$meterId/delete'
    | '/telemetria/$meterId/edit'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)'
    | '/full-plan'
    | '/(dashboard)/supervisorio'
    | '/(dashboard)/telemetria'
    | '/(dashboard)/settings'
    | '/(dashboard)/telemetria/$telemetryIp'
    | '/(dashboard)/gráficos/'
    | '/(dashboard)/supervisorio/'
    | '/(dashboard)/telemetria/'
    | '/(dashboard)/telemetria/$meterId/delete'
    | '/(dashboard)/telemetria/$meterId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  FullPlanRoute: typeof FullPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/full-plan': {
      id: '/full-plan'
      path: '/full-plan'
      fullPath: '/full-plan'
      preLoaderRoute: typeof FullPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/telemetria': {
      id: '/(dashboard)/telemetria'
      path: '/telemetria'
      fullPath: '/telemetria'
      preLoaderRoute: typeof dashboardTelemetriaRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/supervisorio': {
      id: '/(dashboard)/supervisorio'
      path: '/supervisorio'
      fullPath: '/supervisorio'
      preLoaderRoute: typeof dashboardSupervisorioRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/telemetria/': {
      id: '/(dashboard)/telemetria/'
      path: '/'
      fullPath: '/telemetria/'
      preLoaderRoute: typeof dashboardTelemetriaIndexRouteImport
      parentRoute: typeof dashboardTelemetriaRouteRoute
    }
    '/(dashboard)/supervisorio/': {
      id: '/(dashboard)/supervisorio/'
      path: '/'
      fullPath: '/supervisorio/'
      preLoaderRoute: typeof dashboardSupervisorioIndexRouteImport
      parentRoute: typeof dashboardSupervisorioRouteRoute
    }
    '/(dashboard)/gráficos/': {
      id: '/(dashboard)/gráficos/'
      path: '/gráficos'
      fullPath: '/gráficos'
      preLoaderRoute: typeof dashboardGrChar225ficosIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/telemetria/$telemetryIp': {
      id: '/(dashboard)/telemetria/$telemetryIp'
      path: '/$telemetryIp'
      fullPath: '/telemetria/$telemetryIp'
      preLoaderRoute: typeof dashboardTelemetriaTelemetryIpRouteImport
      parentRoute: typeof dashboardTelemetriaRouteRoute
    }
    '/(dashboard)/telemetria/$meterId/edit': {
      id: '/(dashboard)/telemetria/$meterId/edit'
      path: '/$meterId/edit'
      fullPath: '/telemetria/$meterId/edit'
      preLoaderRoute: typeof dashboardTelemetriaMeterIdEditRouteImport
      parentRoute: typeof dashboardTelemetriaRouteRoute
    }
    '/(dashboard)/telemetria/$meterId/delete': {
      id: '/(dashboard)/telemetria/$meterId/delete'
      path: '/$meterId/delete'
      fullPath: '/telemetria/$meterId/delete'
      preLoaderRoute: typeof dashboardTelemetriaMeterIdDeleteRouteImport
      parentRoute: typeof dashboardTelemetriaRouteRoute
    }
  }
}

interface dashboardSupervisorioRouteRouteChildren {
  dashboardSupervisorioIndexRoute: typeof dashboardSupervisorioIndexRoute
}

const dashboardSupervisorioRouteRouteChildren: dashboardSupervisorioRouteRouteChildren =
  {
    dashboardSupervisorioIndexRoute: dashboardSupervisorioIndexRoute,
  }

const dashboardSupervisorioRouteRouteWithChildren =
  dashboardSupervisorioRouteRoute._addFileChildren(
    dashboardSupervisorioRouteRouteChildren,
  )

interface dashboardTelemetriaRouteRouteChildren {
  dashboardTelemetriaTelemetryIpRoute: typeof dashboardTelemetriaTelemetryIpRoute
  dashboardTelemetriaIndexRoute: typeof dashboardTelemetriaIndexRoute
  dashboardTelemetriaMeterIdDeleteRoute: typeof dashboardTelemetriaMeterIdDeleteRoute
  dashboardTelemetriaMeterIdEditRoute: typeof dashboardTelemetriaMeterIdEditRoute
}

const dashboardTelemetriaRouteRouteChildren: dashboardTelemetriaRouteRouteChildren =
  {
    dashboardTelemetriaTelemetryIpRoute: dashboardTelemetriaTelemetryIpRoute,
    dashboardTelemetriaIndexRoute: dashboardTelemetriaIndexRoute,
    dashboardTelemetriaMeterIdDeleteRoute:
      dashboardTelemetriaMeterIdDeleteRoute,
    dashboardTelemetriaMeterIdEditRoute: dashboardTelemetriaMeterIdEditRoute,
  }

const dashboardTelemetriaRouteRouteWithChildren =
  dashboardTelemetriaRouteRoute._addFileChildren(
    dashboardTelemetriaRouteRouteChildren,
  )

interface dashboardRouteRouteChildren {
  dashboardSupervisorioRouteRoute: typeof dashboardSupervisorioRouteRouteWithChildren
  dashboardTelemetriaRouteRoute: typeof dashboardTelemetriaRouteRouteWithChildren
  dashboardSettingsRoute: typeof dashboardSettingsRoute
  dashboardGrChar225ficosIndexRoute: typeof dashboardGrChar225ficosIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardSupervisorioRouteRoute: dashboardSupervisorioRouteRouteWithChildren,
  dashboardTelemetriaRouteRoute: dashboardTelemetriaRouteRouteWithChildren,
  dashboardSettingsRoute: dashboardSettingsRoute,
  dashboardGrChar225ficosIndexRoute: dashboardGrChar225ficosIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  FullPlanRoute: FullPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
