/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LAPES - SCADA api
 * API for supervisory control and data acquisition
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMeters200Item,
  GetMetersGetTelemetryIp200,
  PostMeters201,
  PostMetersBody,
  PutMetersIdBody
} from './model';





/**
 * @summary Register a new meter
 */
export type postMetersResponse201 = {
  data: PostMeters201
  status: 201
}
    
export type postMetersResponseComposite = postMetersResponse201;
    
export type postMetersResponse = postMetersResponseComposite & {
  headers: Headers;
}

export const getPostMetersUrl = () => {


  

  return `http://localhost:3333/meters`
}

export const postMeters = async (postMetersBody: PostMetersBody, options?: RequestInit): Promise<postMetersResponse> => {
  
  const res = await fetch(getPostMetersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postMetersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postMetersResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postMetersResponse
}




export const getPostMetersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeters>>, TError,{data: PostMetersBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postMeters>>, TError,{data: PostMetersBody}, TContext> => {

const mutationKey = ['postMeters'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMeters>>, {data: PostMetersBody}> = (props) => {
          const {data} = props ?? {};

          return  postMeters(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostMetersMutationResult = NonNullable<Awaited<ReturnType<typeof postMeters>>>
    export type PostMetersMutationBody = PostMetersBody
    export type PostMetersMutationError = unknown

    /**
 * @summary Register a new meter
 */
export const usePostMeters = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeters>>, TError,{data: PostMetersBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMeters>>,
        TError,
        {data: PostMetersBody},
        TContext
      > => {

      const mutationOptions = getPostMetersMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get all meters
 */
export type getMetersResponse200 = {
  data: GetMeters200Item[]
  status: 200
}
    
export type getMetersResponseComposite = getMetersResponse200;
    
export type getMetersResponse = getMetersResponseComposite & {
  headers: Headers;
}

export const getGetMetersUrl = () => {


  

  return `http://localhost:3333/meters`
}

export const getMeters = async ( options?: RequestInit): Promise<getMetersResponse> => {
  
  const res = await fetch(getGetMetersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMetersResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMetersResponse
}



export const getGetMetersQueryKey = () => {
    return [`http://localhost:3333/meters`] as const;
    }

    
export const getGetMetersQueryOptions = <TData = Awaited<ReturnType<typeof getMeters>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeters>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeters>>> = ({ signal }) => getMeters({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetersQueryResult = NonNullable<Awaited<ReturnType<typeof getMeters>>>
export type GetMetersQueryError = unknown


export function useGetMeters<TData = Awaited<ReturnType<typeof getMeters>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeters>>,
          TError,
          Awaited<ReturnType<typeof getMeters>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeters<TData = Awaited<ReturnType<typeof getMeters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeters>>,
          TError,
          Awaited<ReturnType<typeof getMeters>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeters<TData = Awaited<ReturnType<typeof getMeters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeters>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all meters
 */

export function useGetMeters<TData = Awaited<ReturnType<typeof getMeters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeters>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMetersQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get raw data from external API
 */
export type getMetersGetTelemetryIpResponse200 = {
  data: GetMetersGetTelemetryIp200
  status: 200
}
    
export type getMetersGetTelemetryIpResponseComposite = getMetersGetTelemetryIpResponse200;
    
export type getMetersGetTelemetryIpResponse = getMetersGetTelemetryIpResponseComposite & {
  headers: Headers;
}

export const getGetMetersGetTelemetryIpUrl = (ip: string,) => {


  

  return `http://localhost:3333/meters/getTelemetry/${ip}`
}

export const getMetersGetTelemetryIp = async (ip: string, options?: RequestInit): Promise<getMetersGetTelemetryIpResponse> => {
  
  const res = await fetch(getGetMetersGetTelemetryIpUrl(ip),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMetersGetTelemetryIpResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMetersGetTelemetryIpResponse
}



export const getGetMetersGetTelemetryIpQueryKey = (ip: string,) => {
    return [`http://localhost:3333/meters/getTelemetry/${ip}`] as const;
    }

    
export const getGetMetersGetTelemetryIpQueryOptions = <TData = Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError = unknown>(ip: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetersGetTelemetryIpQueryKey(ip);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>> = ({ signal }) => getMetersGetTelemetryIp(ip, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(ip), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetersGetTelemetryIpQueryResult = NonNullable<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>>
export type GetMetersGetTelemetryIpQueryError = unknown


export function useGetMetersGetTelemetryIp<TData = Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError = unknown>(
 ip: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetersGetTelemetryIp>>,
          TError,
          Awaited<ReturnType<typeof getMetersGetTelemetryIp>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetersGetTelemetryIp<TData = Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError = unknown>(
 ip: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetersGetTelemetryIp>>,
          TError,
          Awaited<ReturnType<typeof getMetersGetTelemetryIp>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetersGetTelemetryIp<TData = Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError = unknown>(
 ip: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get raw data from external API
 */

export function useGetMetersGetTelemetryIp<TData = Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError = unknown>(
 ip: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetersGetTelemetryIp>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMetersGetTelemetryIpQueryOptions(ip,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update an existing meter
 */
export type putMetersIdResponse200 = {
  data: void
  status: 200
}
    
export type putMetersIdResponseComposite = putMetersIdResponse200;
    
export type putMetersIdResponse = putMetersIdResponseComposite & {
  headers: Headers;
}

export const getPutMetersIdUrl = (id: number,) => {


  

  return `http://localhost:3333/meters/${id}`
}

export const putMetersId = async (id: number,
    putMetersIdBody: PutMetersIdBody, options?: RequestInit): Promise<putMetersIdResponse> => {
  
  const res = await fetch(getPutMetersIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putMetersIdBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: putMetersIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as putMetersIdResponse
}




export const getPutMetersIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putMetersId>>, TError,{id: number;data: PutMetersIdBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putMetersId>>, TError,{id: number;data: PutMetersIdBody}, TContext> => {

const mutationKey = ['putMetersId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putMetersId>>, {id: number;data: PutMetersIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  putMetersId(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutMetersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putMetersId>>>
    export type PutMetersIdMutationBody = PutMetersIdBody
    export type PutMetersIdMutationError = unknown

    /**
 * @summary Update an existing meter
 */
export const usePutMetersId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putMetersId>>, TError,{id: number;data: PutMetersIdBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putMetersId>>,
        TError,
        {id: number;data: PutMetersIdBody},
        TContext
      > => {

      const mutationOptions = getPutMetersIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
