import { z } from 'zod'

export const formattedSchema = z.object({
  tensao_fase_neutro_a: z.number(),
  tensao_fase_neutro_b: z.number(),
  tensao_fase_neutro_c: z.number(),
  tensao_fase_fase_ab: z.number(),
  tensao_fase_fase_bc: z.number(),
  tensao_fase_fase_ca: z.number(),
  frequencia: z.number(),
  corrente_a: z.number(),
  corrente_b: z.number(),
  corrente_c: z.number(),
  corrente_de_neutro_medido: z.number(),
  corrente_de_neutro_calculado: z.number(),
  potencia_aparente_a: z.number(),
  potencia_aparente_b: z.number(),
  potencia_aparente_c: z.number(),
  potencia_aparente_total_soma_aritmetica: z.number(),
  potencia_aparente_total_soma_vetorial: z.number(),
  potencia_ativa_fundamental_a: z.number(),
  potencia_ativa_harmonica_a: z.number(),
  potencia_ativa_fundamental_harmonica_a: z.number(),
  potencia_ativa_fundamental_b: z.number(),
  potencia_ativa_harmonica_b: z.number(),
  potencia_ativa_fundamental_harmonica_b: z.number(),
  potencia_ativa_fundamental_c: z.number(),
  potencia_ativa_harmonica_c: z.number(),
  potencia_ativa_fundamental_harmonica_c: z.number(),
  potencia_ativa_fundamental_total: z.number(),
  potencia_ativa_harmonica_total: z.number(),
  potencia_ativa_fundamental_harmonica_total: z.number(),
  potencia_reativa_a: z.number(),
  potencia_reativa_b: z.number(),
  potencia_reativa_c: z.number(),
  potencia_reativa_total_soma_aritmetica: z.number(),
  potencia_reativa_total_soma_vetorial: z.number(),
  angulo_fase_a: z.number(),
  angulo_fase_b: z.number(),
  angulo_fase_c: z.number(),
  phi_fase_a: z.number(),
  phi_fase_b: z.number(),
  phi_fase_c: z.number(),
  fp_real_fase_a: z.number(),
  fp_real_fase_b: z.number(),
  fp_real_fase_c: z.number(),
  fp_real_total_soma_aritmetica: z.number(),
  fp_real_total_soma_vetorial: z.number(),
  fp_deslocamento_fase_a: z.number(),
  fp_deslocamento_fase_b: z.number(),
  fp_deslocamento_fase_c: z.number(),
  fp_deslocamento_total: z.number(),
  thd_tensao_a: z.number(),
  thd_tensao_b: z.number(),
  thd_tensao_c: z.number(),
  thd_corrente_a: z.number(),
  thd_corrente_b: z.number(),
  thd_corrente_c: z.number(),
  temperatura_sensor_interno: z.number(),
})

export type Formatted = z.infer<typeof formattedSchema>
